import 'dart:convert';

import '../models/qr_validation_code.dart';
import 'hive_storage_service.dart';

/// Persistent storage for QR validation codes.
///
/// Codes are generated by the QR page and are consumed once when an incoming
/// conversation request carries a matching, still-unused code. Storage reuses
/// the existing encrypted Hive box through [HiveStorageService], so the
/// records survive closing the QR page and restarting the app.
class QrValidationCodeService {
  static const String _storageKey = 'qr_validation_codes';

  /// How long USED validation codes are kept in Hive before they are
  /// automatically removed.
  ///
  /// This only applies to codes that have already been consumed. UNUSED
  /// codes are never removed by age.
  static const Duration usedCodeRetentionPeriod = Duration(days: 7);

  Future<List<QrValidationCode>> _loadAll() async {
    final raw =
        HiveStorageService.getStringList(_storageKey) ?? const <String>[];

    final codes = <QrValidationCode>[];

    for (final entry in raw) {
      try {
        codes.add(
          QrValidationCode.fromJson(jsonDecode(entry) as Map<String, dynamic>),
        );
      } catch (_) {
        // Skip malformed records instead of losing the whole store.
      }
    }

    return codes;
  }

  Future<void> _saveAll(List<QrValidationCode> codes) async {
    await HiveStorageService.setStringList(
      _storageKey,
      codes.map((code) => jsonEncode(code.toJson())).toList(),
    );
  }

  /// Persists a freshly generated validation code as UNUSED.
  ///
  /// Older unused codes are left untouched so they stay valid.
  Future<void> registerCode(String validationCode) async {
    if (validationCode.trim().isEmpty) {
      return;
    }

    final codes = await _loadAll();

    final exists = codes.any((code) => code.validationCode == validationCode);

    if (!exists) {
      codes.add(
        QrValidationCode(
          validationCode: validationCode,
          createdAt: DateTime.now(),
          used: false,
          usedAt: null,
        ),
      );
    }

    _removeExpiredUsed(codes);

    await _saveAll(codes);
  }

  /// Returns the stored record for [validationCode], or null if unknown.
  Future<QrValidationCode?> findCode(String validationCode) async {
    if (validationCode.isEmpty) {
      return null;
    }

    final codes = await _loadAll();

    for (final code in codes) {
      if (code.validationCode == validationCode) {
        return code;
      }
    }

    return null;
  }

  /// True when [validationCode] is stored and already consumed.
  Future<bool> isUsed(String validationCode) async {
    final code = await findCode(validationCode);

    return code?.used ?? false;
  }

  /// Marks [validationCode] as used once a conversation has been created.
  Future<bool> markUsed(String validationCode, {DateTime? usedAt}) async {
    final codes = await _loadAll();

    final consumedAt = usedAt ?? DateTime.now();

    var changed = false;

    for (var i = 0; i < codes.length; i++) {
      if (codes[i].validationCode == validationCode && !codes[i].used) {
        codes[i] = QrValidationCode(
          validationCode: codes[i].validationCode,
          createdAt: codes[i].createdAt,
          used: true,
          usedAt: consumedAt,
        );
        changed = true;
      }
    }

    if (!changed) {
      return false;
    }

    _removeExpiredUsed(codes);

    await _saveAll(codes);

    return true;
  }

  /// Removes USED codes whose retention period has elapsed.
  Future<void> removeExpiredUsedCodes() async {
    final codes = await _loadAll();

    final before = codes.length;

    _removeExpiredUsed(codes);

    if (codes.length != before) {
      await _saveAll(codes);
    }
  }

  /// Drops consumed codes older than [usedCodeRetentionPeriod].
  ///
  /// UNUSED codes are always kept, regardless of age.
  void _removeExpiredUsed(List<QrValidationCode> codes) {
    final cutoff = DateTime.now().subtract(usedCodeRetentionPeriod);

    codes.removeWhere(
      (code) =>
          code.used && code.usedAt != null && code.usedAt!.isBefore(cutoff),
    );
  }
}
