/// A persisted QR validation code.
///
/// Every code generated by the QR page is stored once here. A code starts
/// [used] == false and may be consumed exactly once, after which [usedAt]
/// records when it was consumed.
class QrValidationCode {
  final String validationCode;

  final DateTime createdAt;

  final bool used;

  final DateTime? usedAt;

  const QrValidationCode({
    required this.validationCode,
    required this.createdAt,
    required this.used,
    required this.usedAt,
  });

  Map<String, dynamic> toJson() {
    return {
      "validationCode": validationCode,
      "createdAt": createdAt.toIso8601String(),
      "used": used,
      "usedAt": usedAt?.toIso8601String(),
    };
  }

  factory QrValidationCode.fromJson(
    Map<String, dynamic> json,
  ) {
    final rawUsedAt = json["usedAt"];

    return QrValidationCode(
      validationCode:
          json["validationCode"].toString(),
      createdAt: DateTime.parse(
        json["createdAt"].toString(),
      ),
      used: json["used"] == true,
      usedAt: rawUsedAt == null
          ? null
          : DateTime.parse(
              rawUsedAt.toString(),
            ),
    );
  }

  QrValidationCode copyWith({
    String? validationCode,
    DateTime? createdAt,
    bool? used,
    DateTime? usedAt,
  }) {
    return QrValidationCode(
      validationCode:
          validationCode ?? this.validationCode,
      createdAt: createdAt ?? this.createdAt,
      used: used ?? this.used,
      usedAt: usedAt ?? this.usedAt,
    );
  }
}
